export const tableColumns = [
  'ID',
  'Image',
  'Name',
  'Location',
  'Email',
  'Contact No.',
  'Action',
];
export const tableRows = [
  {
    id: '19023867',
    image: '/logo.png',
    name: 'Alpha',
    location: 'Lahore, Pakistan',
    email: 'info@alpha.com',
    contact: '0300-0000000',
    // action: 'View',
  },
  {
    id: '203928409',
    image: '/logo.png',
    name: 'Beta',
    location: 'Lahore, Pakistan',
    email: 'info@beta.com',
    contact: '0300-0000000',
    // action: 'View',
  },
  {
    id: '203928409',
    image: '/logo.png',
    name: 'Beta',
    location: 'Lahore, Pakistan',
    email: 'info@beta.com',
    contact: '0300-0000000',
    // action: 'View',
  },
  {
    id: '203928409',
    image: '/logo.png',
    name: 'Beta',
    location: 'Lahore, Pakistan',
    email: 'info@beta.com',
    contact: '0300-0000000',
    // action: 'View',
  },
  {
    id: '203928409',
    image: '/logo.png',
    name: 'Beta',
    location: 'Lahore, Pakistan',
    email: 'info@beta.com',
    contact: '0300-0000000',
    // action: 'View',
  },
  {
    id: '10',
    image: '/logo.png',
    name: 'Gamma',
    location: 'Lahore, Pakistan',
    email: 'info@beta.com',
    contact: '0300-1234567',
    // action: 'View',
  },
  {
    id: '20',
    image: '/logo.png',
    name: 'AestheTeQs',
    location: 'Lahore, Pakistan',
    email: 'info@aestheteqs.com',
    contact: '0321-9861201',
    // action: 'View',
  },
];
