export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const CATEGORY_LIST_RESET = 'CATEGORY_LIST_RESET';

export const CATEGORY_DETAILS_LIST__SUCCESS = 'CATEGORY_DETAILS_LIST_SUCCESS';
export const CATEGORY_DETAILS_LIST_FAIL = 'CATEGORY_DETAILS_LIST_FAIL';
export const CATEGORY_DETAILS_LIST_RESET = 'CATEGORY_DETAILS_LIST_RESET';

export const CATEGORY_DETAILS__SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';
export const CATEGORY_DETAILS_RESET = 'CATEGORY_DETAILS_RESET';

export const CATEGORY_FETCH__SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL';
export const CATEGORY_FETCH_RESET = 'CATEGORY_FETCH_RESET';

export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET';
