export const ASSET_CREATE_SUCCESS = 'ASSET_CREATE_SUCCESS';
export const ASSET_CREATE_FAIL = 'ASSET_CREATE_FAIL';
export const ASSET_CREATE_RESET = 'ASSET_CREATE_RESET';

export const ASSET_LIST_SUCCESS = 'ASSET_LIST_SUCCESS';
export const ASSET_LIST_FAIL = 'ASSET_LIST_FAIL';
export const ASSET_LIST_RESET = 'ASSET_LIST_RESET';

export const ASSET_DETAILS_REQUEST = 'ASSET_DETAILS_REQUEST';
export const ASSET_DETAILS_SUCCESS = 'ASSET_DETAILS_SUCCESS';
export const ASSET_DETAILS_FAIL = 'ASSET_DETAILS_FAIL';
