export const SUBCATEGORY_DETAILS__SUCCESS = 'SUBCATEGORY_DETAILS_SUCCESS';
export const SUBCATEGORY_DETAILS_FAIL = 'SUBCATEGORY_DETAILS_FAIL';
export const SUBCATEGORY_DETAILS_RESET = 'SUBCATEGORY_DETAILS_RESET';
