export const SUBCATEGORY_DETAILS__SUCCESS = 'SUBCATEGORY_DETAILS_SUCCESS';
export const SUBCATEGORY_DETAILS_FAIL = 'SUBCATEGORY_DETAILS_FAIL';
export const SUBCATEGORY_DETAILS_RESET = 'SUBCATEGORY_DETAILS_RESET';

export const SUBCATEGORY_ADD_SUCCESS = 'SUBCATEGORY_ADD_SUCCESS';
export const SUBCATEGORY_ADD_FAIL = 'SUBCATEGORY_ADD_FAIL';
export const SUBCATEGORY_ADD_RESET = 'SUBCATEGORY_ADD_RESET';

export const SUBCATEGORY_DELETE_SUCCESS = 'SUBCATEGORY_DELETE_SUCCESS';
export const SUBCATEGORY_DELETE_FAIL = 'SUBCATEGORY_DELETE_FAIL';
export const SUBCATEGORY_DELETE_RESET = 'SUBCATEGORY_DELETE_RESET';
