export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS';
export const ORGANIZATION_LIST_FAIL = 'ORGANIZATION_LIST_FAIL';
export const ORGANIZATION_LIST_RESET = 'ORGANIZATION_LIST_RESET';

export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS';
export const ORGANIZATION_CREATE_FAIL = 'ORGANIZATION_CREATE_FAIL';
export const ORGANIZATION_CREATE_RESET = 'ORGANIZATION_CREATE_RESET';

export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS';
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_FAIL';
