export const COMPLAINT_CREATE_SUCCESS = 'COMPLAINT_CREATE_SUCCESS';
export const COMPLAINT_CREATE_FAIL = 'COMPLAINT_CREATE_FAIL';
export const COMPLAINT_CREATE_RESET = 'COMPLAINT_CREATE_RESET';

export const COMPLAINT_LIST_SUCCESS = 'COMPLAINT_LIST_SUCCESS';
export const COMPLAINT_LIST_FAIL = 'COMPLAINT_LIST_FAIL';
export const COMPLAINT_LIST_RESET = 'COMPLAINT_LIST_RESET';

export const COMPLAINT_DETAILS_REQUEST = 'COMPLAINT_DETAILS_REQUEST';
export const COMPLAINT_DETAILS_SUCCESS = 'COMPLAINT_DETAILS_SUCCESS';
export const COMPLAINT_DETAILS_FAIL = 'COMPLAINT_DETAILS_FAIL';

export const COMPLAINT_UPDATE_REQUEST = 'COMPLAINT_UPDATE_REQUEST';
export const COMPLAINT_UPDATE_SUCCESS = 'COMPLAINT_UPDATE_SUCCESS';
export const COMPLAINT_UPDATE_FAIL = 'COMPLAINT_UPDATE_FAIL';
export const COMPLAINT_UPDATE_RESET = 'COMPLAINT_UPDATE_RESET';
