export const REQUESTS_CREATE_SUCCESS = 'REQUESTS_CREATE_SUCCESS';
export const REQUESTS_CREATE_FAIL = 'REQUESTS_CREATE_FAIL';
export const REQUESTS_CREATE_RESET = 'REQUESTS_CREATE_RESET';

export const REQUESTS_LIST_SUCCESS = 'REQUESTS_LIST_SUCCESS';
export const REQUESTS_LIST_FAIL = 'REQUESTS_LIST_FAIL';
export const REQUESTS_LIST_RESET = 'REQUESTS_LIST_RESET';

export const REQUESTS_DETAILS_REQUEST = 'REQUESTS_DETAILS_REQUEST';
export const REQUESTS_DETAILS_SUCCESS = 'REQUESTS_DETAILS_SUCCESS';
export const REQUESTS_DETAILS_FAIL = 'REQUESTS_DETAILS_FAIL';

export const REQUESTS_UPDATE_REQUEST = 'REQUESTS_UPDATE_REQUEST';
export const REQUESTS_UPDATE_SUCCESS = 'REQUESTS_UPDATE_SUCCESS';
export const REQUESTS_UPDATE_FAIL = 'REQUESTS_UPDATE_FAIL';
export const REQUESTS_UPDATE_RESET = 'REQUESTS_UPDATE_RESET';
