export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_FAIL = 'DASHBOARD_DATA_FAIL';
export const DASHBOARD_DATA_RESET = 'DASHBOARD_DATA_RESET';

export const DASHBOARD_STATS_SUCCESS = 'DASHBOARD_STATS_SUCCESS';
export const DASHBOARD_STATS_FAIL = 'DASHBOARD_STATS_FAIL';
export const DASHBOARD_STATS_RESET = 'DASHBOARD_STATS_RESET';
