export const PASSWORD_RESET_TOKEN_CREATE_SUCCESS =
  'PASSWORD_RESET_TOKEN_CREATE_SUCCESS';
export const PASSWORD_RESET_TOKEN_CREATE_FAIL =
  'PASSWORD_RESET_TOKEN_CREATE_FAIL';
export const PASSWORD_RESET_TOKEN_CREATE_RESET =
  'PASSWORD_RESET_TOKEN_CREATE_RESET';

export const PASSWORD_RESET_TOKEN_VERIFY_SUCCESS =
  'PASSWORD_RESET_TOKEN_VERIFY_SUCCESS';
export const PASSWORD_RESET_TOKEN_VERIFY_FAIL =
  'PASSWORD_RESET_TOKEN_VERIFY_FAIL';
export const PASSWORD_RESET_TOKEN_VERIFY_RESET =
  'PASSWORD_RESET_TOKEN_VERIFY_RESET';
