export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS';
export const DEPARTMENT_LIST_FAIL = 'DEPARTMENT_LIST_FAIL';
export const DEPARTMENT_LIST_RESET = 'DEPARTMENT_LIST_RESET';

export const DEPARTMENT_CREATE_SUCCESS = 'DEPARTMENT_CREATE_SUCCESS';
export const DEPARTMENT_CREATE_FAIL = 'DEPARTMENT_CREATE_FAIL';
export const DEPARTMENT_CREATE_RESET = 'DEPARTMENT_CREATE_RESET';
